# Generated by Django 4.2.7 on 2023-12-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weekend_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
